name: Demo Workflow

on:
  push:
    branches:
      - main  # or master, depending on your default branch
  workflow_dispatch:  # lets you trigger manually

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 23f2000866@ds.study.iitm.ac.in
        run: echo "Hello, world! Workflow is running."
